# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20161128_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active_inner_products',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
